repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.7.1
#    hooks:
#      - id: mypy
#        additional_dependencies:
#          - typing-extensions
#  - repo: https://github.com/jumanjihouse/pre-commit-hooks
#    rev: 3.0.0
#    hooks:
#      - id: shellcheck
#        files: ^experiments/
#        types: [ shell ]
#      - id: shfmt
#        files: ^experiments/
#        types: [ shell ]
#        args: [ -i 2 -sr ]
